import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'zh-TW' | 'en' | 'ja' | 'ko';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

const translations: Record<Language, Record<string, string>> = {
  'zh-TW': {
    'mainMenu.title': 'OLAF TOURISM PLANNER',
    'mainMenu.subtitle': '旅遊規劃助手',
    'mainMenu.plan': '自行規劃行程',
    'mainMenu.aiPlan': 'AI 推薦行程',
    'mainMenu.history': '查看行程記錄',
    'mainMenu.settings': 'API 金鑰設定',
    'tripList.title': '所有行程',
    'tripList.current': '當前',
    'tripList.noTrips': '尚無行程記錄',
    'tripList.spent': '花費',
    'tripList.distance': '距離',
    'tripList.total': '總計',
    'tripList.totalSpent': '總花費',
    'tripList.totalDistance': '總距離',
    'tripList.days': '天',
    'flight.title': '查詢航班信息',
    'flight.flightNumber': '航班編號',
    'flight.date': '查詢日期',
    'flight.search': '查詢航班信息',
    'flight.searching': '查詢中...',
    'flight.departure': '出發',
    'flight.arrival': '抵達',
    'flight.status': '狀態',
    'flight.onTime': '準時',
    'flight.delayed': '延誤',
    'flight.terminal': '航廈',
    'flight.gate': '登機門',
    'flight.checkIn': '報到櫃檯',
    'flight.baggageClaim': '行李轉盤',
    'flight.scheduledTime': '計劃時間',
    'flight.actualTime': '實際時間',
    'flight.baggageInfo': '行李資訊',
    'flight.baggageAllowance': '行李限額',
    'flight.carryOn': '隨身行李',
    'flight.checkedBaggage': '託運行李',
    'flight.routeMap': '機場路線圖',
    'flight.apiSelect': '查詢方式',
    'flight.apiAirLabs': 'AirLabs',
    'flight.apiSerpAPI': 'SerpAPI (含延誤資訊)',
    'flight.dateNote': '注意：AirLabs API 目前不支持日期參數，將查詢實時航班信息',
    'flight.dateNoteSerpAPI': 'SerpAPI 支持日期查詢，將查詢指定日期的航班信息（實時狀態來自 AirLabs，僅顯示當天數據）',
    'flight.dateWarning': '您選擇的是未來日期（{date}），實時狀態信息僅顯示當天數據',
    'flight.dateWarningPast': '您選擇的是過去日期（{date}），實時狀態信息僅顯示當天數據',
    'flight.transportCost': '交通費用',
    'flight.errorNoFlightNumber': '請輸入航班編號',
    'flight.errorQueryFailed': '查詢航班信息失敗',
    'flight.errorOccurred': '查詢航班信息時發生錯誤',
  },
  'en': {
    'mainMenu.title': 'OLAF TOURISM PLANNER',
    'mainMenu.subtitle': 'Travel Planning Assistant',
    'mainMenu.plan': 'Self-Plan Itinerary',
    'mainMenu.aiPlan': 'AI Recommended Itinerary',
    'mainMenu.history': 'View Trip History',
    'mainMenu.settings': 'API Key Settings',
    'tripList.title': 'All Trips',
    'tripList.current': 'Current',
    'tripList.noTrips': 'No trip records yet',
    'tripList.spent': 'Spent',
    'tripList.distance': 'Distance',
    'tripList.total': 'Total',
    'tripList.totalSpent': 'Total Spent',
    'tripList.totalDistance': 'Total Distance',
    'tripList.days': 'days',
    'flight.title': 'Flight Information',
    'flight.flightNumber': 'Flight Number',
    'flight.date': 'Date',
    'flight.search': 'Search Flight',
    'flight.searching': 'Searching...',
    'flight.departure': 'Departure',
    'flight.arrival': 'Arrival',
    'flight.status': 'Status',
    'flight.onTime': 'On Time',
    'flight.delayed': 'Delayed',
    'flight.terminal': 'Terminal',
    'flight.gate': 'Gate',
    'flight.checkIn': 'Check-in Counter',
    'flight.baggageClaim': 'Baggage Claim',
    'flight.scheduledTime': 'Scheduled Time',
    'flight.actualTime': 'Actual Time',
    'flight.baggageInfo': 'Baggage Information',
    'flight.baggageAllowance': 'Baggage Allowance',
    'flight.carryOn': 'Carry-on',
    'flight.checkedBaggage': 'Checked Baggage',
    'flight.routeMap': 'Airport Route Map',
    'flight.apiSelect': 'API Selection',
    'flight.apiAirLabs': 'AirLabs',
    'flight.apiSerpAPI': 'SerpAPI (with Delay Info)',
    'flight.dateNote': 'Note: AirLabs API does not support date parameter, will query real-time flight information',
    'flight.dateNoteSerpAPI': 'SerpAPI supports date query, will query flight information for the specified date (real-time status from AirLabs, shows only today\'s data)',
    'flight.dateWarning': 'You selected a future date ({date}), real-time status information shows only today\'s data',
    'flight.dateWarningPast': 'You selected a past date ({date}), real-time status information shows only today\'s data',
    'flight.transportCost': 'Transport Cost',
    'flight.errorNoFlightNumber': 'Please enter flight number',
    'flight.errorQueryFailed': 'Failed to query flight information',
    'flight.errorOccurred': 'An error occurred while querying flight information',
  },
  'ja': {
    'mainMenu.title': 'OLAF TOURISM PLANNER',
    'mainMenu.subtitle': '旅行計画アシスタント',
    'mainMenu.plan': '自分で計画する',
    'mainMenu.aiPlan': 'AI推奨プラン',
    'mainMenu.history': '旅行履歴を見る',
    'mainMenu.settings': 'APIキー設定',
    'tripList.title': 'すべての旅行',
    'tripList.current': '現在',
    'tripList.noTrips': 'まだ旅行記録がありません',
    'tripList.spent': '費用',
    'tripList.distance': '距離',
    'tripList.total': '合計',
    'tripList.totalSpent': '総費用',
    'tripList.totalDistance': '総距離',
    'tripList.days': '日',
    'flight.title': 'フライト情報検索',
    'flight.flightNumber': 'フライト番号',
    'flight.date': '検索日',
    'flight.search': 'フライト情報を検索',
    'flight.searching': '検索中...',
    'flight.departure': '出発',
    'flight.arrival': '到着',
    'flight.status': 'ステータス',
    'flight.onTime': '定時',
    'flight.delayed': '遅延',
    'flight.terminal': 'ターミナル',
    'flight.gate': 'ゲート',
    'flight.checkIn': 'チェックインカウンター',
    'flight.baggageClaim': '手荷物受取所',
    'flight.scheduledTime': '予定時間',
    'flight.actualTime': '実際の時間',
    'flight.baggageInfo': '手荷物情報',
    'flight.baggageAllowance': '手荷物許容量',
    'flight.carryOn': '機内持ち込み',
    'flight.checkedBaggage': '預け入れ手荷物',
    'flight.routeMap': '空港ルートマップ',
    'flight.apiSelect': 'API選択',
    'flight.apiAirLabs': 'AirLabs',
    'flight.apiSerpAPI': 'SerpAPI（遅延情報含む）',
    'flight.dateNote': '注意：AirLabs APIは現在日付パラメータをサポートしていません。リアルタイムのフライト情報を照会します',
    'flight.dateNoteSerpAPI': 'SerpAPIは日付検索をサポートしています。指定した日付のフライト情報を照会します（リアルタイムステータスはAirLabsから、当日のデータのみ表示）',
    'flight.dateWarning': '未来の日付（{date}）を選択しました。リアルタイムステータス情報は当日のデータのみ表示されます',
    'flight.dateWarningPast': '過去の日付（{date}）を選択しました。リアルタイムステータス情報は当日のデータのみ表示されます',
    'flight.transportCost': '交通費',
    'flight.errorNoFlightNumber': 'フライト番号を入力してください',
    'flight.errorQueryFailed': 'フライト情報の照会に失敗しました',
    'flight.errorOccurred': 'フライト情報の照会中にエラーが発生しました',
  },
  'ko': {
    'mainMenu.title': 'OLAF TOURISM PLANNER',
    'mainMenu.subtitle': '여행 계획 어시스턴트',
    'mainMenu.plan': '자체 계획 일정',
    'mainMenu.aiPlan': 'AI 추천 일정',
    'mainMenu.history': '여행 기록 보기',
    'mainMenu.settings': 'API 키 설정',
    'tripList.title': '모든 여행',
    'tripList.current': '현재',
    'tripList.noTrips': '아직 여행 기록이 없습니다',
    'tripList.spent': '비용',
    'tripList.distance': '거리',
    'tripList.total': '합계',
    'tripList.totalSpent': '총 비용',
    'tripList.totalDistance': '총 거리',
    'tripList.days': '일',
    'flight.title': '항공편 정보 조회',
    'flight.flightNumber': '항공편 번호',
    'flight.date': '조회 날짜',
    'flight.search': '항공편 정보 조회',
    'flight.searching': '조회 중...',
    'flight.departure': '출발',
    'flight.arrival': '도착',
    'flight.status': '상태',
    'flight.onTime': '정시',
    'flight.delayed': '지연',
    'flight.terminal': '터미널',
    'flight.gate': '게이트',
    'flight.checkIn': '체크인 카운터',
    'flight.baggageClaim': '수하물 수취',
    'flight.scheduledTime': '예정 시간',
    'flight.actualTime': '실제 시간',
    'flight.baggageInfo': '수하물 정보',
    'flight.baggageAllowance': '수하물 허용량',
    'flight.carryOn': '기내 휴대',
    'flight.checkedBaggage': '위탁 수하물',
    'flight.routeMap': '공항 경로 지도',
    'flight.apiSelect': 'API 선택',
    'flight.apiAirLabs': 'AirLabs',
    'flight.apiSerpAPI': 'SerpAPI (지연 정보 포함)',
    'flight.dateNote': '참고: AirLabs API는 현재 날짜 매개변수를 지원하지 않습니다. 실시간 항공편 정보를 조회합니다',
    'flight.dateNoteSerpAPI': 'SerpAPI는 날짜 조회를 지원합니다. 지정한 날짜의 항공편 정보를 조회합니다 (실시간 상태는 AirLabs에서, 당일 데이터만 표시)',
    'flight.dateWarning': '미래 날짜({date})를 선택했습니다. 실시간 상태 정보는 당일 데이터만 표시됩니다',
    'flight.dateWarningPast': '과거 날짜({date})를 선택했습니다. 실시간 상태 정보는 당일 데이터만 표시됩니다',
    'flight.transportCost': '교통비',
    'flight.errorNoFlightNumber': '항공편 번호를 입력하세요',
    'flight.errorQueryFailed': '항공편 정보 조회 실패',
    'flight.errorOccurred': '항공편 정보 조회 중 오류가 발생했습니다',
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'zh-TW',
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'travelgenie-language',
    }
  )
);

export function t(key: string): string {
  const state = useLanguageStore.getState();
  return translations[state.language][key] || key;
}

